-- Görevlerin saklanacağı tablo
create table if not exists todos (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- Satır bazlı güvenlik (RLS) açık
alter table todos enable row level security;

-- Bu basit uygulama için tarayıcıdan (anon anahtarıyla) okuma/yazmaya izin ver
create policy "anon_todos_all"
  on todos
  for all
  to anon
  using (true)
  with check (true);
